### ISSUE TITLE
[PENDING] One-liner expression type ascription

### ISSUE THREAD

**Issue by Centril** [rust-lang/style-team#135]
cc @joshtriplett 

If https://github.com/rust-lang/rfcs/pull/2522 should be accepted, the style team could think about how to format type ascription when it occurs on one line, e.g.

```rust
let _ = ("1234".parse().unwrap() : usize).into() : Box<_>;
let _ = "1234".parse().unwrap(): usize.into(): Box<_>;
```

(current discussion seems to go for the first option)

Alternatively, `rustfmt` could just break this into several lines:

```rust
let _ = "1234".parse().unwrap(): usize
    .into(): Box<_>;
```

**Comment by joshtriplett** [comment]
On December 24, 2018 7:26:16 AM PST, Alexander Regueiro <notifications@github.com> wrote:
>I'm not in the style team obviously, but I'm definitely in favour of
>the second. We don't promote a space before a colon in any other
>scenario.

We do in type signatures.

**Comment by alexreg** [comment]
> We do in type signatures.

Really? Eww. I don't see it much in the "wild" though.

**Comment by compiler-errors** [comment]
Type ascription is no longer :)
