### ISSUE TITLE
Consider using human/natural sort order

### ISSUE THREAD

**Issue by tanriol** [rust-lang/style-team#143]
Names used in libraries quite often contain numbers. In general, a sequence of digits in a name seems to be usually a number, not just a sequence of digits. However, rustfmt's sort order does not take that into account. For example, if I import several nom parsers for various integers, rustfmt suggests the following order

```
use nom::number::complete::{le_u128, le_u16, le_u32, le_u64, le_u8};
```

which feels really weird compared to

```
use nom::number::complete::{le_u8, le_u16, le_u32, le_u64, le_u128};
```

It would be great if the rustfmt sort order matched the natural expectations.

**Comment by tanriol** [comment]
Hm. Looking at the linked documentation

> Digits are determined by the `isdigit` function and are thus subject to the current locale.

is my expectation correct that `rustfmt` should not rely on the environment locale and should sort according to some default?

Also, what's the process here? Is anything needed before implementation and rustfmt PR?

**Comment by tanriol** [comment]
Would it be better to depend on some crate providing natural/version sort or to write an internal function for that?

**Comment by joshtriplett** [comment]
@tanriol I meant that as a general description of the algorithm. I would expect us to use 0-9 here for now, and I think we can implement the algorithm ourselves in Rust unless there's a crate handy that you already know of.

**Comment by tanriol** [comment]
Working on a PR and testing it, I'm seeing [contradictions](https://github.com/rust-lang/rustfmt/blob/master/tests/target/imports-reorder-lines.rs#L16-L25) between actual tests and comment in them. Which ones should I follow?

**Comment by tanriol** [comment]
The PR is up as rust-lang/rustfmt#3764.

**Comment by calebcartwright** [comment]
Closing as I believe this issue has served its purposed. The Style Team agreed, decided upon a matching sort algorithm, set that as the default for Style Edition 2024 and beyond, and it's now been fully implemented within rustfmt (n.b. there's still an unstable option [reorder_impl_items](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#reorder_impl_items) that needs to switch to this new algorithm, but all stable sorting formatting applies this new algorithm)
